version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine
    - 15.13.0.pre.alpine
    - 15.6.0.pre.alpine
    - 15.7.0.pre.alpine
    - 15.8.0.pre.alpine
    - 15.9.0.pre.alpine
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.3
    - 3.13.4
