services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app/
  docs:
    build:
      context: .
      target: docs
    volumes:
      - .:/app/

  golangci-lint:
    image: golangci/golangci-lint:v1.54.1
    working_dir: /app/
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app/
