# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGitmojiCli < Formula
  desc "CLI for managing commits gitmoji and conventional commits format"
  homepage "https://github.com/AndreasAugustin/go-gitmoji-cli"
  version "0.3.1-alpha"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.1-alpha/go-gitmoji-cli_0.3.1-alpha_Darwin_x86_64.tar.gz"
      sha256 "7a952c14cef5a40658fc36ee826344671ee4b45bab0ae15242fc000ef51d597b"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.1-alpha/go-gitmoji-cli_0.3.1-alpha_Darwin_arm64.tar.gz"
      sha256 "a648ca43168a993ba86b32d0dd93fcf7d9b255fe24cc779427ba2274d797834e"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.1-alpha/go-gitmoji-cli_0.3.1-alpha_Linux_arm64.tar.gz"
      sha256 "0bffd18f6093fd1ca8fc5f4d057d56819c93bdbd55e2d691473ce412433e3d97"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.1-alpha/go-gitmoji-cli_0.3.1-alpha_Linux_x86_64.tar.gz"
      sha256 "6a739a01d5c4c7c3184a9429f7ccc5920fd0e6d8cd981f2bfafbceaabb49d0c7"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
  end
end
