# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGitmojiCli < Formula
  desc "CLI for managing commits gitmoji and conventional commits format"
  homepage "https://github.com/AndreasAugustin/go-gitmoji-cli"
  version "0.3.2-alpha"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.2-alpha/go-gitmoji-cli_0.3.2-alpha_Darwin_x86_64.tar.gz"
      sha256 "ca6e16ecf4a2faa6b3965fefa126c1717c7d6b570de15924d68f8945ed5f61f3"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.2-alpha/go-gitmoji-cli_0.3.2-alpha_Darwin_arm64.tar.gz"
      sha256 "8e10806177a1fcf6f97c976315d61b7877ae7ac158f24b25bb608bb1bd025f87"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.2-alpha/go-gitmoji-cli_0.3.2-alpha_Linux_arm64.tar.gz"
      sha256 "d84d5d4f60d50276ef5082c93dcc7a25a9f48e40924b5f802411383488585d28"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AndreasAugustin/go-gitmoji-cli/releases/download/v0.3.2-alpha/go-gitmoji-cli_0.3.2-alpha_Linux_x86_64.tar.gz"
      sha256 "6a2c09b5626693d23f03502862cb936b60e582b18bd7741eca0ff67e79911fc8"

      def install
        bin.install "go-gitmoji-cli"
        bash_completion.install "completions/go-gitmoji-cli.bash" => "go-gitmoji-cli"
        zsh_completion.install "completions/go-gitmoji-cli.zsh" => "_go-gitmoji-cli"
        fish_completion.install "completions/go-gitmoji-cli.fish"
        man1.install "manpages/go-gitmoji-cli.1.gz"
      end
    end
  end
end
