name: ci_go

on: [push, pull_request]

jobs:
  go:
    strategy:
      matrix:
        go_version: [ '1.20', '1.19' ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - run: go build -o dist/
      - run: go test ./... -cover
