name: goreleaser

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The dockerhub username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'The dockerhub token'
        required: true
      AUR_KEY:
        description: 'The AUR key'
        required: true
      NFPM_GPG_KEY:
        description: 'The NFPM GPG key'
        required: true
      NFPM_DEFAULT_PASSPHRASE:
        description: 'The NFPM GPG pass phrase'
        required: true
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: git fetch --force --tags
      - run: |
          echo "$NFPM_GPG_KEY" > ${{ runner.temp }}/nfpm_gpg.key
        env:
          NFPM_GPG_KEY: ${{ secrets.NFPM_GPG_KEY }}
      - uses: anchore/sbom-action/download-syft@v0.15.11
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          NFPM_GPG_KEY_PATH: ${{ runner.temp }}/nfpm_gpg.key
          NFPM_DEFAULT_PASSPHRASE: ${{ secrets.NFPM_DEFAULT_PASSPHRASE }}
