name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker image tag'
        required: true
        type: string
        default: v0.2.8-alpha-amd64
#  push:
#    branches:
#      - main

jobs:
  call-ci-go:
    uses: ./.github/workflows/ci_go.yml
  call-lint:
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/lint.yml
  release-please:
    needs:
      - call-ci-go
      - call-lint
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/release_please.yml
  release-go:
    if: ${{ jobs.release-please.outputs.release_created }}
    needs:
      - release-go
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/release_go.yml
    secrets: inherit
  call-test-docker-images:
    if: ${{ jobs.release-please.outputs.release_created || inputs.tag }}
    needs:
      - release-go
    permissions:
      packages: read
    uses: ./.github/workflows/test_docker_images.yml
    with:
      tag: ${{ jobs.release-please.outputs.tag_name || inputs.tag }}
    secrets: inherit
